packages:
  - apps/**
  - packages/**
  - tooling/**
  - supabase
  - e2e
catalog:
  '@tanstack/react-query': ^5.62.8
  '@trpc/client': ^11.0.0-rc.666
  '@trpc/react-query': ^11.0.0-rc.666
  '@trpc/server': ^11.0.0-rc.666
  '@turbo/gen': ^2.3.3
  eslint: ^9.9.0
  lucide-react: ^0.462.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.7.3
  superjson: ^2.2.1
  zod: ^3.24.2
catalogs:
  react:
    next: ^15.2.4
    react: ^19.0.0
    react-dom: ^19.0.0
    '@types/react': ^19.0.0
    '@types/react-dom': ^19.0.0
  payload3:
    '@payloadcms/db-vercel-postgres': ^3.14.0
    '@payloadcms/live-preview-react': ^3.14.0
    '@payloadcms/next': ^3.9.0
    '@payloadcms/plugin-form-builder': ^3.14.0
    '@payloadcms/plugin-nested-docs': ^3.14.0
    '@payloadcms/plugin-redirects': ^3.14.0
    '@payloadcms/plugin-search': ^3.14.0
    '@payloadcms/plugin-seo': ^3.14.0
    '@payloadcms/richtext-lexical': ^3.14.0
    '@payloadcms/storage-s3': ^3.14.0
    payload: ^3.14.0
